apiVersion: v1
kind: Deployment

metadata:
  name: chat-agent-zeroto-test
  namespace: development

spec:
  repoUrl: https://github.com/ManyamSanjayKumarReddy/langgraph_agent.git
  tag: latest
  replicas: 1
  cpu: 1
  memory: 512
  port: 8003

  labels:
    app: chat-agent

  config: chatagent_config
  secret: chatagent_secret

  volumeMounts:
    - name: app-uploads
      mountPath: /app/uploads
    - name: app-data
      mountPath: /app/data
    - name: app-chroma
      mountPath: /app/chroma_db

  service:
    name: chat-agent

  ingress:
    name: chatagent-ingress
    host: demo.theskilledguru.com
    path: /chat
    tls: true

cicd:
  branch: main
  event: push
  webhookSecret: random-webhooksecret